- name: Install system packages, Node.js, and create user
  hosts: all
  become: yes
  tasks:

    - name: Update apt cache and install ACL support
      apt:
        name:
          - acl
        state: present
        update_cache: yes

    - name: Install Node.js and npm
      apt:
        name:
          - nodejs
          - npm

    - name: Create user attia with sudo privileges
      user:
        name: attia
        groups: sudo
        create_home: yes

    - name: Ensure /home/attia is world-accessible
      file:
        path: /home/attia
        state: directory
        owner: attia
        group: attia
        mode: '0755'

    - name: Ensure .npm cache folder for attia exists
      file:
        path: /home/attia/.npm
        state: directory
        owner: attia
        group: attia
        mode: '0755'

    - name: Recursively fix ownership of .npm folder for attia
      file:
        path: /home/attia/.npm
        state: directory
        owner: attia
        group: attia
        recurse: yes

    - name: Copy application archive to home directory
      copy:
        src: app.tar.gz
        dest: /home/attia/app.tar.gz

    - name: Extract application archive
      unarchive:
        src: /home/attia/app.tar.gz
        dest: /home/attia
        remote_src: yes

    - name: Install Node.js dependencies (run as root for dev)
      shell: npm install
      args:
        chdir: /home/attia/app

    - name: Start Node.js application as root (dev only)
      shell: |
        cd /home/attia/app
        nohup node server.js &
      args:
        executable: /bin/bash

